apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosaic-common-service.fullname" . }}-config
  labels:
    {{- include "mosaic-common-service.labels" . | nindent 4 }}
data:
  GATEWAY_REDSHIFT_HOST: {{ .Values.config.redshiftHost | quote }}
  GATEWAY_REDSHIFT_PORT: {{ .Values.config.redshiftPort | quote }}
  GATEWAY_REDSHIFT_DATABASE: {{ .Values.config.redshiftDatabase | quote }}
  GATEWAY_POOL_MIN_CONNS: {{ .Values.config.poolMinConns | quote }}
  GATEWAY_POOL_MAX_CONNS: {{ .Values.config.poolMaxConns | quote }}
  GATEWAY_QUERY_TIMEOUT_SECONDS: {{ .Values.config.queryTimeoutSeconds | quote }}
  GATEWAY_AUDIT_LOG_TABLE: {{ .Values.config.auditLogTable | quote }}
  GATEWAY_REDSHIFT_CREDENTIALS_FILE: {{ .Values.config.credentialsFilePath | quote }}
